version: '3.8'

services:
  opensearch:
    image: opensearchproject/opensearch:2.11.0
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
    volumes:
      - opensearch-data:/usr/share/opensearch/data
    networks:
      - avapt-network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPENSEARCH_URL=http://opensearch:9200
      - LAB_MODE=true
      - SHODAN_API_KEY=${SHODAN_API_KEY:-}
    depends_on:
      - opensearch
    networks:
      - avapt-network

  streamlit:
    build: 
      context: .
      dockerfile: streamlit_app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - avapt-network
    volumes:
      - ./streamlit_app:/app
      - ./data:/app/data

volumes:
  opensearch-data:

networks:
  avapt-network:
    driver: bridge